import streamlit as st
import requests
import pandas as pd
import plotly.graph_objects as go
import json
import os

# Configure Page
st.set_page_config(
    page_title="Project Gyan | AI Investment System",
    page_icon="🔮",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Use the docker service name to connect to API
API_URL = "http://setu_api:8000"

# Custom CSS for "GenZ/Modern" Vibe
st.markdown("""
<style>
    .big-font { font-size:30px !important; font-weight: bold; }
    .verdict-box { padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 20px; }
    .buy { background-color: #00C853; color: white; }
    .sell { background-color: #D50000; color: white; }
    .hold { background-color: #FFD600; color: black; }
</style>
""", unsafe_allow_html=True)

st.title("🔮 Project Gyan: AI Investment System")

# --- HELPER FUNCTIONS ---
def safe_format(value, fmt="{:.2f}", default="N/A"):
    """Safely formats a value, returning default if None."""
    if value is None:
        return default
    return fmt.format(value)

# --- TABS ---
tab1, tab2, tab3 = st.tabs(["🚀 Deep Analysis", "🔎 Stock Finder", "💼 Portfolio"])

# --- TAB 1: DEEP ANALYSIS ---
with tab1:
    st.header("Deep Analysis & Investment Guide")
    
    col1, col2 = st.columns([3, 1])
    with col1:
        ticker_input = st.text_input("Enter Ticker (e.g. RELIANCE.NS)", value="RELIANCE.NS")
    with col2:
        analyze_btn = st.button("Analyze Stock", use_container_width=True, type="primary")

    if analyze_btn:
        try:
            with st.spinner("Consulting the AI Brain..."):
                # Call our Setu API
                res = requests.get(f"{API_URL}/analysis/{ticker_input}")
                
                if res.status_code == 200:
                    data = res.json()
                    
                    # 1. The verdict Banner
                    verdict = data.get('verdict', 'UNKNOWN')
                    confidence = data.get('confidence', 0)
                    
                    if verdict == "BUY": color_class = "buy"
                    elif verdict == "SELL": color_class = "sell"
                    else: color_class = "hold"
                    
                    st.markdown(f"""
                    <div class="verdict-box {color_class}">
                        <div class="big-font">{verdict}</div>
                        <div>AI Confidence: {safe_format(confidence, '{:.1f}')}%</div>
                    </div>
                    """, unsafe_allow_html=True)
                    
                    # 2. Key Metrics
                    m1, m2, m3, m4 = st.columns(4)
                    
                    curr_price = data.get('current_price')
                    tgt_price = data.get('target_price')
                    rsi_val = data.get('rsi')
                    
                    m1.metric("Current Price", f"₹{safe_format(curr_price)}")
                    m2.metric("Target Price (30d)", f"₹{safe_format(tgt_price)}")
                    
                    # Calculate Upside safely
                    upside_str = "N/A"
                    if curr_price and tgt_price and curr_price > 0:
                        upside = ((tgt_price - curr_price) / curr_price) * 100
                        upside_str = f"{upside:.1f}%"
                        
                    m3.metric("Potential Upside", upside_str)
                    m4.metric("RSI (Technical)", safe_format(rsi_val, "{:.1f}"))

                    # 3. Reasoning
                    st.subheader("🤖 AI Reasoning")
                    st.info(data.get('reasoning', "No reasoning available."))
                    
                    st.caption(f"Last Updated: {data.get('last_updated', 'Never')}")

                else:
                    st.error(f"Stock '{ticker_input}' not found in database. It will be added in the next Nightly Hunt.")
                    
        except Exception as e:
            st.error(f"Error connecting to API: {e}")

# --- TAB 2: STOCK FINDER ---
with tab2:
    st.header("AI Stock Screener")
    st.write("Scan the market for high-confidence BUY signals generated by the Nightly Engine.")
    
    if st.button("Run AI Scanner"):
        with st.spinner("Scanning database..."):
            try:
                res = requests.get(f"{API_URL}/screener/buy")
                if res.status_code == 200:
                    opportunities = res.json()
                    if opportunities:
                        df = pd.DataFrame(opportunities)
                        st.dataframe(df, use_container_width=True)
                    else:
                        st.warning("No high-confidence BUY signals found today.")
            except Exception as e:
                 st.error(f"API Error: {e}")

# --- TAB 3: PORTFOLIO ---
with tab3:
    st.header("My Portfolio Intelligence")
    
    if st.button("Refresh Portfolio"):
        try:
            if not os.path.exists('portfolio.json'):
                 st.warning("portfolio.json not found. Please create one.")
            else:
                with open('portfolio.json', 'r') as f:
                    holdings = json.load(f)
                
                portfolio_data = []
                total_invested = 0
                total_value = 0
                
                with st.spinner("Analyzing your holdings..."):
                    for item in holdings:
                        # Call API for each stock
                        try:
                            res = requests.get(f"{API_URL}/analysis/{item['ticker']}")
                            if res.status_code == 200:
                                data = res.json()
                                cur_price = data.get('current_price', 0) or 0
                                tgt_price = data.get('target_price', 0) or 0
                                
                                value = cur_price * item['quantity']
                                invested = item['buy_price'] * item['quantity']
                                pl = value - invested
                                pl_pct = (pl / invested) * 100 if invested > 0 else 0
                                
                                total_invested += invested
                                total_value += value
                                
                                portfolio_data.append({
                                    "Ticker": item['ticker'],
                                    "Qty": item['quantity'],
                                    "Buy Price": item['buy_price'],
                                    "Cur. Price": cur_price,
                                    "P/L": round(pl, 2),
                                    "P/L %": round(pl_pct, 2),
                                    "AI Verdict": data.get('verdict', 'N/A'),
                                    "Target": tgt_price
                                })
                        except:
                            st.warning(f"Could not fetch data for {item['ticker']}")
                
                # Summary Metrics
                t1, t2, t3 = st.columns(3)
                total_pl = total_value - total_invested
                t1.metric("Total Value", f"₹{total_value:,.0f}")
                t2.metric("Total Invested", f"₹{total_invested:,.0f}")
                t3.metric("Total P/L", f"₹{total_pl:,.0f}", delta=f"{(total_pl/total_invested)*100:.1f}%" if total_invested > 0 else "0%")
                
                # Detailed Table
                if portfolio_data:
                    st.dataframe(pd.DataFrame(portfolio_data), use_container_width=True)
            
        except Exception as e:
            st.error(f"Error loading portfolio: {e}")