"""Max Power Upgrade

Revision ID: 06131515d986
Revises: e990b8fd1380
Create Date: 2025-12-07 10:36:13.269675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06131515d986'
down_revision: Union[str, Sequence[str], None] = 'e990b8fd1380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_data', sa.Column('predicted_close', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('ensemble_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_data', 'ensemble_score')
    op.drop_column('fundamental_data', 'predicted_close')
    # ### end Alembic commands ###
