"""Add catalyst event table

Revision ID: 4cdd6ccc9828
Revises: 63333debbbd2
Create Date: 2026-01-03 12:41:12.630886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdd6ccc9828'
down_revision: Union[str, Sequence[str], None] = '63333debbbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalyst_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalyst_events_id'), 'catalyst_events', ['id'], unique=False)
    op.create_index(op.f('ix_catalyst_events_ticker'), 'catalyst_events', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalyst_events_ticker'), table_name='catalyst_events')
    op.drop_index(op.f('ix_catalyst_events_id'), table_name='catalyst_events')
    op.drop_table('catalyst_events')
    # ### end Alembic commands ###
