"""Create_Full_Schema

Revision ID: 862565cd728e
Revises: 
Create Date: 2025-11-23 11:52:09.774881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862565cd728e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('st_verdict', sa.String(), nullable=True),
    sa.Column('st_target', sa.Float(), nullable=True),
    sa.Column('st_stoploss', sa.Float(), nullable=True),
    sa.Column('st_days', sa.Integer(), nullable=True),
    sa.Column('mt_verdict', sa.String(), nullable=True),
    sa.Column('mt_target', sa.Float(), nullable=True),
    sa.Column('mt_stoploss', sa.Float(), nullable=True),
    sa.Column('mt_days', sa.Integer(), nullable=True),
    sa.Column('lt_verdict', sa.String(), nullable=True),
    sa.Column('lt_target', sa.Float(), nullable=True),
    sa.Column('lt_stoploss', sa.Float(), nullable=True),
    sa.Column('lt_days', sa.Integer(), nullable=True),
    sa.Column('ai_verdict', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_data_id'), 'fundamental_data', ['id'], unique=False)
    op.create_index(op.f('ix_fundamental_data_ticker'), 'fundamental_data', ['ticker'], unique=True)
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='_ticker_date_uc')
    )
    op.create_index(op.f('ix_stock_data_date'), 'stock_data', ['date'], unique=False)
    op.create_index(op.f('ix_stock_data_id'), 'stock_data', ['id'], unique=False)
    op.create_index(op.f('ix_stock_data_ticker'), 'stock_data', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_data_ticker'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_id'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_date'), table_name='stock_data')
    op.drop_table('stock_data')
    op.drop_index(op.f('ix_fundamental_data_ticker'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_id'), table_name='fundamental_data')
    op.drop_table('fundamental_data')
    # ### end Alembic commands ###
