"""Add Fundamental Metrics

Revision ID: b0fdc7c9fa0c
Revises: 862565cd728e
Create Date: 2025-11-23 15:04:59.248279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fdc7c9fa0c'
down_revision: Union[str, Sequence[str], None] = '862565cd728e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_data', sa.Column('roe', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('debt_to_equity', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('free_cash_flow', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('revenue_growth', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_data', 'revenue_growth')
    op.drop_column('fundamental_data', 'free_cash_flow')
    op.drop_column('fundamental_data', 'debt_to_equity')
    op.drop_column('fundamental_data', 'roe')
    # ### end Alembic commands ###
