"""Phase 4.5 Full Upgrade

Revision ID: bba1ff143fff
Revises: b0fdc7c9fa0c
Create Date: 2025-11-25 16:53:52.654162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba1ff143fff'
down_revision: Union[str, Sequence[str], None] = 'b0fdc7c9fa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_data', sa.Column('piotroski_f_score', sa.Integer(), nullable=True))
    op.add_column('fundamental_data', sa.Column('altman_z_score', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('beneish_m_score', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('score_fundamental', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('score_technical', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('score_growth', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('score_risk', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('score_news', sa.Float(), nullable=True))
    op.drop_column('fundamental_data', 'revenue_growth')
    op.drop_column('fundamental_data', 'roe')
    op.drop_column('fundamental_data', 'free_cash_flow')
    op.drop_column('fundamental_data', 'debt_to_equity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_data', sa.Column('debt_to_equity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamental_data', sa.Column('free_cash_flow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamental_data', sa.Column('roe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamental_data', sa.Column('revenue_growth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('fundamental_data', 'score_news')
    op.drop_column('fundamental_data', 'score_risk')
    op.drop_column('fundamental_data', 'score_growth')
    op.drop_column('fundamental_data', 'score_technical')
    op.drop_column('fundamental_data', 'score_fundamental')
    op.drop_column('fundamental_data', 'beneish_m_score')
    op.drop_column('fundamental_data', 'altman_z_score')
    op.drop_column('fundamental_data', 'piotroski_f_score')
    # ### end Alembic commands ###
