"""Add Sector Performance

Revision ID: dc0bbb27ba59
Revises: 06131515d986
Create Date: 2025-12-16 16:55:48.621955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc0bbb27ba59'
down_revision: Union[str, Sequence[str], None] = '06131515d986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_performance_id'), 'sector_performance', ['id'], unique=False)
    op.create_index(op.f('ix_sector_performance_sector_name'), 'sector_performance', ['sector_name'], unique=True)
    op.drop_table('decision_audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_audit',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shap_values', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_audit_pkey'))
    )
    op.drop_index(op.f('ix_sector_performance_sector_name'), table_name='sector_performance')
    op.drop_index(op.f('ix_sector_performance_id'), table_name='sector_performance')
    op.drop_table('sector_performance')
    # ### end Alembic commands ###
