"""Database changes

Revision ID: ed77d4a4d48e
Revises: 4cdd6ccc9828
Create Date: 2026-02-07 16:48:44.281349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed77d4a4d48e'
down_revision: Union[str, Sequence[str], None] = '4cdd6ccc9828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('instrument_type', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('tp_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('selected_algo', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('indicators_used', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('square_off_time', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_trades_uuid'), 'trades', ['uuid'], unique=False)
    op.add_column('fundamental_data', sa.Column('pledge_pct', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('interest_coverage', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('fii_holding', sa.Float(), nullable=True))
    op.add_column('sector_performance', sa.Column('sector_pe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sector_performance', 'sector_pe')
    op.drop_column('fundamental_data', 'fii_holding')
    op.drop_column('fundamental_data', 'interest_coverage')
    op.drop_column('fundamental_data', 'pledge_pct')
    op.drop_index(op.f('ix_trades_uuid'), table_name='trades')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
