"""Add AI verdict columns

Revision ID: fa6624ecf32a
Revises: 90c541e56c9d
Create Date: 2025-11-22 13:10:10.823335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6624ecf32a'
down_revision: Union[str, Sequence[str], None] = '90c541e56c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_data', sa.Column('ai_verdict', sa.String(), nullable=True))
    op.add_column('fundamental_data', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('fundamental_data', sa.Column('ai_reasoning', sa.String(), nullable=True))
    op.add_column('fundamental_data', sa.Column('last_updated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_data', 'last_updated')
    op.drop_column('fundamental_data', 'ai_reasoning')
    op.drop_column('fundamental_data', 'target_price')
    op.drop_column('fundamental_data', 'ai_confidence')
    op.drop_column('fundamental_data', 'ai_verdict')
    # ### end Alembic commands ###
