import requests
import json
from shared.news_utils import fetch_news_rss

import os

# Helper to call Ollama
OLLAMA_HOST = os.environ.get('OLLAMA_HOST', 'ollama')
OLLAMA_URL = f"http://{OLLAMA_HOST}:11434/api/generate"
MODEL_NAME = "llama3"


BLACKLIST_KEYWORDS = ["SEBI Ban", "Insolvency", "NCLT", "CBI", "ED Raid", "Promoter Arrest", "Forensic Audit"]

def generate_ai_catalyst(ticker, news_items=None):
    """
    Analyzes news headlines to extract a Strategic Catalyst.
    Returns: (score, context)
        score: 0 (None), 1 (Good), 2 (Mega/Strategic), -5 (Toxic)
        context: Description of the catalyst or None
    """
    
    if not news_items:
        try:
            news_items = fetch_news_rss(ticker)
        except Exception as e:
            print(f"AI Catalyst: News fetch failed for {ticker}: {e}")
            return 0, None

    if not news_items:
        return 0, None # No news, no catalyst

    # Prepare Context for LLM
    headlines = [f"- {item.get('title', '')}" for item in news_items[:8]] # Top 8 headlines
    headlines_text = "\n".join(headlines)

    prompt = f"""
    You are a Forensic Financial Auditor and Strategist.
    Analyze the following news for {ticker} using the "Forensic & Integrity" Framework.
    
    NEWS SUMMARY:
    {headlines_text}
    
    TASK 1: FORENSIC SENTINEL (Capital Protection)
    Search for evidence of:
    1. Legal Finality: SEBI Bans, Heavy Fines, Regulatory Orders.
    2. Solvency Crisis: Loan Defaults, Insolvency (NCLT), Bankruptcy, Debt Restructuring.
    3. Integrity Breach: Fraud, ED Raids, CBI Investigation, Promoter Arrests, Auditor Resignation.
    
    Classify 'Forensic Risk' as:
    - TOXIC (-5): Confirmed Breach (e.g., "SEBI Bans Promoter", "Defaults on Payment", "Fraud Accepted").
    - MODERATE (-2): Potential Threat (e.g., "Show Cause Notice", "Unconfirmed Raid", "Profit Warning", "Auditor Concerns").
    - NEUTRAL (0): No integrity or solvency issues found.
    
    TASK 2: STRATEGIC CATALYST (Growth)
    If Risk is NEUTRAL, identify the biggest positive driver:
    - MEGA (2): Merger/Acquisition, Massive Order Win (>10% Market Cap), Government PLI, Demerger.
    - GOOD (1): Strong Earnings, New Product, Partnership.
    - NONE (0): No major catalyst.
    
    OUTPUT JSON FORMAT (Strictly):
    {{
        "forensic_risk": "TOXIC" | "MODERATE" | "NEUTRAL",
        "forensic_reasoning": "<Concise verification of risk>",
        "catalyst_score": 2 | 1 | 0,
        "catalyst_context": "<Concise description of growth driver>"
    }}
    """
    
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "format": "json", 
        "options": {"temperature": 0.1}
    }
    
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=120)
        if response.status_code == 200:
            res_json = response.json()
            llm_text = res_json.get('response', '')
            with open("debug_ai_log.txt", "w", encoding="utf-8") as f:
                f.write(f"LLM RESPONSE:\n{llm_text}\n")
            
            # Simple manual JSON parsing (robustness)
            import json
            try:
                # Try to find JSON object in text
                start = llm_text.find('{')
                end = llm_text.rfind('}') + 1
                if start != -1 and end != -1:
                    data = json.loads(llm_text[start:end])
                    
                    # 1. Check Forensic Risk First
                    risk_level = data.get('forensic_risk', 'NEUTRAL').upper()
                    risk_reason = data.get('forensic_reasoning', 'No specific risk.')
                    
                    if risk_level == "TOXIC":
                        return -5, f"TOXIC (FORENSIC): {risk_reason}"
                    
                    if risk_level == "MODERATE":
                        return -2, f"RISK (FORENSIC): {risk_reason}"
                        
                    # 2. If Neutral, Return Catalyst
                    score = int(data.get('catalyst_score', 0))
                    context = data.get('catalyst_context', 'Generated by AI')
                    
                    # Prefix context with score type for UI
                    if score == 2: prefix = "STRATEGIC (AI): "
                    elif score == 1: prefix = "GROWTH (AI): "
                    else: prefix = ""
                    
                    return score, prefix + context
                    
            except:
                print(f"AI Catalyst: JSON Parse Error for {ticker}. Raw: {llm_text}")
                
        return 0, None
        
    except Exception as e:
        with open("debug_ai_log.txt", "w", encoding="utf-8") as f:
            f.write(f"ERROR: Inference failed: {e}\n")
        print(f"AI Catalyst: Inference failed: {e}")
        return 0, None
