# services/engine_astra/stock_list.py

# A robust list of NIFTY 50 tickers.
# We will start with these. We can easily expand this to 500 later.
NIFTY50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
    "LTIM.NS", "HCLTECH.NS", "BAJFINANCE.NS", "AXISBANK.NS", "ASIANPAINT.NS",
    "MARUTI.NS", "BAJAJFINSV.NS", "WIPRO.NS", "SUNPHARMA.NS", "TITAN.NS",
    "ULTRACEMCO.NS", "ADANIENT.NS", "NESTLEIND.NS", "ONGC.NS", "TATAMOTORS.NS",
    "NTPC.NS", "JSWSTEEL.NS", "POWERGRID.NS", "TATASTEEL.NS", "COALINDIA.NS",
    "M&M.NS", "ADANIPORTS.NS", "INDUSINDBK.NS", "GRASIM.NS", "HINDALCO.NS",
    "LT.NS", "CIPLA.NS", "PIDILITIND.NS", "BAJAJ-AUTO.NS", "SBILIFE.NS",
    "DRREDDY.NS", "BPCL.NS", "HDFCLIFE.NS", "EICHERMOT.NS", "SHREECEM.NS",
    "BRITANNIA.NS", "HEROMOTOCO.NS", "DIVISLAB.NS", "APOLLOHOSP.NS", "UPL.NS"
]